/* eslint-disable */
// Generated by Wrangler by running `wrangler types --strict-vars false --include-runtime false` (hash: 09d2a4367f7a2ea42a9ecda5118790a2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		KV: KVNamespace;
		GIT_COMMIT_SHA: string;
		GIT_BRANCH: string;
		LOGFIRE_TOKEN: string;
		LOGFIRE_ENVIRONMENT: string;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
