blank_issues_enabled: false
contact_links:
  - name: 💬 Join Slack
    url: 'https://logfire.pydantic.dev/docs/join-slack/'
    about: Join our Slack community to ask questions, get help, and chat about Pydantic AI
